language: go

go:
  - "1.8"

env:
  global:
    - GH_REF: github.com/nickxwei/nickxwei.github.io

# Specify which branches to build using a safelist
branches:
  only:
    - master

install:
  - wget -qO- https://api.github.com/repos/gohugoio/hugo/releases/latest | sed -r -n '/browser_download_url/{/Linux-64bit.deb/{s@[^:]*:[[:space:]]*"([^"]*)".*@\1@g;p;q}}' | xargs wget
  - sudo dpkg -i hugo*.deb

script:
  - hugo

after_script:
  - cd ./public
  - git init
  - git config user.name "nickxwei"
  - git config user.email "invalidwei@gmail.com"
  - git add .
  - git commit -m "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  - git push --force --quiet "https://$GITHUB_TOKEN@${GH_REF}" master:master

