language: go

go:
  - "1.8"

env:
  global:
    - GH_REF: https://github.com/nickxwei/nickxwei.github.io

# Specify which branches to build using a safelist
branches:
  only:
    - master

install:
  - go get -u -v github.com/spf13/hugo
  - git submodule add https://github.com/Track3/hermit.git themes/hermit

script:
  - hugo

after_script:
  - cd ./public
  - git init
  - git config "[nickxwei]"
  - git config "[invalidwei@gmail.com]"
  - git add .
  - git comit -m "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  #Github Pages
  - git push --force --quiet "https://$GITHUB_TOKEN@${GH_REF}" master:master
  - git push --quiet "https://$GITHUB_TOKEN@${GH_REF}" master:master --tags

